function createfigure1(X1, YMatrix1, sampleStart,sampleEnd)
%CREATEFIGURE1(X1, YMATRIX1)
%  X1:  vector of x data YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 30-Aug-2013 15:32:55

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'Color',[1 0 0]);
set(plot1(2),'Color',[0 0 1]);

% Create xlabel
xlabel({'event time (s)'});

% Create ylabel
ylabel({'P15/P15L (red)','P15H (blue)'});

% create title string
points=sampleEnd-sampleStart+1;
title_string=sprintf('Low-Side Current Plot (t=%d samples, begin=%d, end=%d)',points,sampleStart,sampleEnd);

% Create title
title({title_string;'from RD532-MAPERS-2 8/22/2013 data set';'for NASA ARC EEL MCATPE subsystem test (PPUV7.2, THG2.2)'});

